// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTestTree = "test_tree"

// TestTree 测试树表
type TestTree struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:主键" json:"id"`                     // 主键
	TenantID   string    `gorm:"column:tenant_id;default:000000;comment:租户编号" json:"tenant_id"` // 租户编号
	ParentID   int64     `gorm:"column:parent_id;comment:父id" json:"parent_id"`                 // 父id
	DeptID     int64     `gorm:"column:dept_id;comment:部门id" json:"dept_id"`                    // 部门id
	UserID     int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                    // 用户id
	TreeName   string    `gorm:"column:tree_name;comment:值" json:"tree_name"`                   // 值
	Version    int32     `gorm:"column:version;comment:版本" json:"version"`                      // 版本
	CreateDept int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`            // 创建部门
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`            // 创建时间
	CreateBy   int64     `gorm:"column:create_by;comment:创建人" json:"create_by"`                 // 创建人
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`            // 更新时间
	UpdateBy   int64     `gorm:"column:update_by;comment:更新人" json:"update_by"`                 // 更新人
	DelFlag    int32     `gorm:"column:del_flag;comment:删除标志" json:"del_flag"`                  // 删除标志
}

// TableName TestTree's table name
func (*TestTree) TableName() string {
	return TableNameTestTree
}
