// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTestDemo = "test_demo"

// TestDemo 测试单表
type TestDemo struct {
	ID         int64     `gorm:"column:id;primaryKey;comment:主键" json:"id"`                     // 主键
	TenantID   string    `gorm:"column:tenant_id;default:000000;comment:租户编号" json:"tenant_id"` // 租户编号
	DeptID     int64     `gorm:"column:dept_id;comment:部门id" json:"dept_id"`                    // 部门id
	UserID     int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                    // 用户id
	OrderNum   int32     `gorm:"column:order_num;comment:排序号" json:"order_num"`                 // 排序号
	TestKey    string    `gorm:"column:test_key;comment:key键" json:"test_key"`                  // key键
	Value      string    `gorm:"column:value;comment:值" json:"value"`                           // 值
	Version    int32     `gorm:"column:version;comment:版本" json:"version"`                      // 版本
	CreateDept int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`            // 创建部门
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`            // 创建时间
	CreateBy   int64     `gorm:"column:create_by;comment:创建人" json:"create_by"`                 // 创建人
	UpdateTime time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`            // 更新时间
	UpdateBy   int64     `gorm:"column:update_by;comment:更新人" json:"update_by"`                 // 更新人
	DelFlag    int32     `gorm:"column:del_flag;comment:删除标志" json:"del_flag"`                  // 删除标志
}

// TableName TestDemo's table name
func (*TestDemo) TableName() string {
	return TableNameTestDemo
}
