// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: desc/system/rpc/desc.proto

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysRpc_UserInfo_FullMethodName      = "/system.SysRpc/UserInfo"
	SysRpc_ClientInfo_FullMethodName    = "/system.SysRpc/ClientInfo"
	SysRpc_SysLogin_FullMethodName      = "/system.SysRpc/SysLogin"
	SysRpc_TenantList_FullMethodName    = "/system.SysRpc/TenantList"
	SysRpc_LoginInfoSave_FullMethodName = "/system.SysRpc/LoginInfoSave"
	SysRpc_OperLogSave_FullMethodName   = "/system.SysRpc/OperLogSave"
)

// SysRpcClient is the client API for SysRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysRpcClient interface {
	UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	ClientInfo(ctx context.Context, in *ClientInfoReq, opts ...grpc.CallOption) (*ClientInfoResp, error)
	SysLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	TenantList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*TenantListResp, error)
	LoginInfoSave(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*EmptyResp, error)
	OperLogSave(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*EmptyResp, error)
}

type sysRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSysRpcClient(cc grpc.ClientConnInterface) SysRpcClient {
	return &sysRpcClient{cc}
}

func (c *sysRpcClient) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, SysRpc_UserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRpcClient) ClientInfo(ctx context.Context, in *ClientInfoReq, opts ...grpc.CallOption) (*ClientInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientInfoResp)
	err := c.cc.Invoke(ctx, SysRpc_ClientInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRpcClient) SysLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, SysRpc_SysLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRpcClient) TenantList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*TenantListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantListResp)
	err := c.cc.Invoke(ctx, SysRpc_TenantList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRpcClient) LoginInfoSave(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysRpc_LoginInfoSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysRpcClient) OperLogSave(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysRpc_OperLogSave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysRpcServer is the server API for SysRpc service.
// All implementations must embed UnimplementedSysRpcServer
// for forward compatibility.
type SysRpcServer interface {
	UserInfo(context.Context, *UserInfoReq) (*UserInfoResp, error)
	ClientInfo(context.Context, *ClientInfoReq) (*ClientInfoResp, error)
	SysLogin(context.Context, *LoginReq) (*LoginResp, error)
	TenantList(context.Context, *EmptyReq) (*TenantListResp, error)
	LoginInfoSave(context.Context, *LoginInfoReq) (*EmptyResp, error)
	OperLogSave(context.Context, *OperLogReq) (*EmptyResp, error)
	mustEmbedUnimplementedSysRpcServer()
}

// UnimplementedSysRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysRpcServer struct{}

func (UnimplementedSysRpcServer) UserInfo(context.Context, *UserInfoReq) (*UserInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedSysRpcServer) ClientInfo(context.Context, *ClientInfoReq) (*ClientInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClientInfo not implemented")
}
func (UnimplementedSysRpcServer) SysLogin(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SysLogin not implemented")
}
func (UnimplementedSysRpcServer) TenantList(context.Context, *EmptyReq) (*TenantListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TenantList not implemented")
}
func (UnimplementedSysRpcServer) LoginInfoSave(context.Context, *LoginInfoReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginInfoSave not implemented")
}
func (UnimplementedSysRpcServer) OperLogSave(context.Context, *OperLogReq) (*EmptyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method OperLogSave not implemented")
}
func (UnimplementedSysRpcServer) mustEmbedUnimplementedSysRpcServer() {}
func (UnimplementedSysRpcServer) testEmbeddedByValue()                {}

// UnsafeSysRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysRpcServer will
// result in compilation errors.
type UnsafeSysRpcServer interface {
	mustEmbedUnimplementedSysRpcServer()
}

func RegisterSysRpcServer(s grpc.ServiceRegistrar, srv SysRpcServer) {
	// If the following call panics, it indicates UnimplementedSysRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysRpc_ServiceDesc, srv)
}

func _SysRpc_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_UserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).UserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysRpc_ClientInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).ClientInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_ClientInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).ClientInfo(ctx, req.(*ClientInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysRpc_SysLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).SysLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_SysLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).SysLogin(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysRpc_TenantList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).TenantList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_TenantList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).TenantList(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysRpc_LoginInfoSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).LoginInfoSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_LoginInfoSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).LoginInfoSave(ctx, req.(*LoginInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysRpc_OperLogSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysRpcServer).OperLogSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysRpc_OperLogSave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysRpcServer).OperLogSave(ctx, req.(*OperLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysRpc_ServiceDesc is the grpc.ServiceDesc for SysRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.SysRpc",
	HandlerType: (*SysRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserInfo",
			Handler:    _SysRpc_UserInfo_Handler,
		},
		{
			MethodName: "ClientInfo",
			Handler:    _SysRpc_ClientInfo_Handler,
		},
		{
			MethodName: "SysLogin",
			Handler:    _SysRpc_SysLogin_Handler,
		},
		{
			MethodName: "TenantList",
			Handler:    _SysRpc_TenantList_Handler,
		},
		{
			MethodName: "LoginInfoSave",
			Handler:    _SysRpc_LoginInfoSave_Handler,
		},
		{
			MethodName: "OperLogSave",
			Handler:    _SysRpc_OperLogSave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "desc/system/rpc/desc.proto",
}
