// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type DemoBase struct {
	ID       int64  `json:"id,optional"`       // 主键
	OrderNum string `json:"orderNum,optional"` // 排序号
	TestKey  string `json:"testKey,optional"`  // key键
	Value    string `json:"value,optional"`    // 值
	Version  string `json:"version,optional"`  // 版本
}

type DemoQuery struct {
	OrderNum string `form:"orderNum,optional"` // 排序号
	TestKey  string `form:"testKey,optional"`  // key键
	Value    string `form:"value,optional"`    // 值
	Version  string `form:"version,optional"`  // 版本
}

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id string `path:"id"`
}

type IdsReq struct {
	Ids string `path:"ids"`
}

type ListTreeReq struct {
	TreeQuery
}

type ModifyDemoReq struct {
	DemoBase
}

type ModifyTreeReq struct {
	TreeBase
}

type PageReq struct {
	PageNum  int64 `form:"pageNum,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
	TimeReq
}

type PageSetDemoReq struct {
	PageReq
	DemoQuery
}

type PageSetDemoResp struct {
	Rows  []*DemoBase `json:"rows"`
	Total int64       `json:"total"`
}

type TimeReq struct {
	BeginTime string `form:"params[beginTime],optional"`
	EndTime   string `form:"params[endTime],optional"`
}

type TreeBase struct {
	ID       int64  `json:"id,optional"` // 主键
	ParentID int64  `json:"parentId,optional"`
	DeptID   string `json:"deptId,optional"`   // 部门id
	UserID   string `json:"userId,optional"`   // 用户id
	TreeName string `json:"treeName,optional"` // 值
	Version  string `json:"version,optional"`  // 版本
}

type TreeQuery struct {
	ParentID string `form:"parentId,optional"`
	DeptID   string `form:"deptId,optional"`   // 部门id
	UserID   string `form:"userId,optional"`   // 用户id
	TreeName string `form:"treeName,optional"` // 值
	Version  string `form:"version,optional"`
}
