// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/demo/internal/dal/model"
)

func newTestTree(db *gorm.DB, opts ...gen.DOOption) testTree {
	_testTree := testTree{}

	_testTree.testTreeDo.UseDB(db, opts...)
	_testTree.testTreeDo.UseModel(&model.TestTree{})

	tableName := _testTree.testTreeDo.TableName()
	_testTree.ALL = field.NewAsterisk(tableName)
	_testTree.ID = field.NewInt64(tableName, "id")
	_testTree.TenantID = field.NewString(tableName, "tenant_id")
	_testTree.ParentID = field.NewInt64(tableName, "parent_id")
	_testTree.DeptID = field.NewInt64(tableName, "dept_id")
	_testTree.UserID = field.NewInt64(tableName, "user_id")
	_testTree.TreeName = field.NewString(tableName, "tree_name")
	_testTree.Version = field.NewInt32(tableName, "version")
	_testTree.CreateDept = field.NewInt64(tableName, "create_dept")
	_testTree.CreateTime = field.NewTime(tableName, "create_time")
	_testTree.CreateBy = field.NewInt64(tableName, "create_by")
	_testTree.UpdateTime = field.NewTime(tableName, "update_time")
	_testTree.UpdateBy = field.NewInt64(tableName, "update_by")
	_testTree.DelFlag = field.NewInt32(tableName, "del_flag")

	_testTree.fillFieldMap()

	return _testTree
}

// testTree 测试树表
type testTree struct {
	testTreeDo testTreeDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	TenantID   field.String // 租户编号
	ParentID   field.Int64  // 父id
	DeptID     field.Int64  // 部门id
	UserID     field.Int64  // 用户id
	TreeName   field.String // 值
	Version    field.Int32  // 版本
	CreateDept field.Int64  // 创建部门
	CreateTime field.Time   // 创建时间
	CreateBy   field.Int64  // 创建人
	UpdateTime field.Time   // 更新时间
	UpdateBy   field.Int64  // 更新人
	DelFlag    field.Int32  // 删除标志

	fieldMap map[string]field.Expr
}

func (t testTree) Table(newTableName string) *testTree {
	t.testTreeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t testTree) As(alias string) *testTree {
	t.testTreeDo.DO = *(t.testTreeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *testTree) updateTableName(table string) *testTree {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TenantID = field.NewString(table, "tenant_id")
	t.ParentID = field.NewInt64(table, "parent_id")
	t.DeptID = field.NewInt64(table, "dept_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.TreeName = field.NewString(table, "tree_name")
	t.Version = field.NewInt32(table, "version")
	t.CreateDept = field.NewInt64(table, "create_dept")
	t.CreateTime = field.NewTime(table, "create_time")
	t.CreateBy = field.NewInt64(table, "create_by")
	t.UpdateTime = field.NewTime(table, "update_time")
	t.UpdateBy = field.NewInt64(table, "update_by")
	t.DelFlag = field.NewInt32(table, "del_flag")

	t.fillFieldMap()

	return t
}

func (t *testTree) WithContext(ctx context.Context) *testTreeDo { return t.testTreeDo.WithContext(ctx) }

func (t testTree) TableName() string { return t.testTreeDo.TableName() }

func (t testTree) Alias() string { return t.testTreeDo.Alias() }

func (t testTree) Columns(cols ...field.Expr) gen.Columns { return t.testTreeDo.Columns(cols...) }

func (t *testTree) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *testTree) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 13)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["parent_id"] = t.ParentID
	t.fieldMap["dept_id"] = t.DeptID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["tree_name"] = t.TreeName
	t.fieldMap["version"] = t.Version
	t.fieldMap["create_dept"] = t.CreateDept
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["create_by"] = t.CreateBy
	t.fieldMap["update_time"] = t.UpdateTime
	t.fieldMap["update_by"] = t.UpdateBy
	t.fieldMap["del_flag"] = t.DelFlag
}

func (t testTree) clone(db *gorm.DB) testTree {
	t.testTreeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t testTree) replaceDB(db *gorm.DB) testTree {
	t.testTreeDo.ReplaceDB(db)
	return t
}

type testTreeDo struct{ gen.DO }

func (t testTreeDo) Debug() *testTreeDo {
	return t.withDO(t.DO.Debug())
}

func (t testTreeDo) WithContext(ctx context.Context) *testTreeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t testTreeDo) ReadDB() *testTreeDo {
	return t.Clauses(dbresolver.Read)
}

func (t testTreeDo) WriteDB() *testTreeDo {
	return t.Clauses(dbresolver.Write)
}

func (t testTreeDo) Session(config *gorm.Session) *testTreeDo {
	return t.withDO(t.DO.Session(config))
}

func (t testTreeDo) Clauses(conds ...clause.Expression) *testTreeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t testTreeDo) Returning(value interface{}, columns ...string) *testTreeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t testTreeDo) Not(conds ...gen.Condition) *testTreeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t testTreeDo) Or(conds ...gen.Condition) *testTreeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t testTreeDo) Select(conds ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t testTreeDo) Where(conds ...gen.Condition) *testTreeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t testTreeDo) Order(conds ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t testTreeDo) Distinct(cols ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t testTreeDo) Omit(cols ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t testTreeDo) Join(table schema.Tabler, on ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t testTreeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t testTreeDo) RightJoin(table schema.Tabler, on ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t testTreeDo) Group(cols ...field.Expr) *testTreeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t testTreeDo) Having(conds ...gen.Condition) *testTreeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t testTreeDo) Limit(limit int) *testTreeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t testTreeDo) Offset(offset int) *testTreeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t testTreeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *testTreeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t testTreeDo) Unscoped() *testTreeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t testTreeDo) Create(values ...*model.TestTree) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t testTreeDo) CreateInBatches(values []*model.TestTree, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t testTreeDo) Save(values ...*model.TestTree) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t testTreeDo) First() (*model.TestTree, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestTree), nil
	}
}

func (t testTreeDo) Take() (*model.TestTree, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestTree), nil
	}
}

func (t testTreeDo) Last() (*model.TestTree, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestTree), nil
	}
}

func (t testTreeDo) Find() ([]*model.TestTree, error) {
	result, err := t.DO.Find()
	return result.([]*model.TestTree), err
}

func (t testTreeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TestTree, err error) {
	buf := make([]*model.TestTree, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t testTreeDo) FindInBatches(result *[]*model.TestTree, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t testTreeDo) Attrs(attrs ...field.AssignExpr) *testTreeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t testTreeDo) Assign(attrs ...field.AssignExpr) *testTreeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t testTreeDo) Joins(fields ...field.RelationField) *testTreeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t testTreeDo) Preload(fields ...field.RelationField) *testTreeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t testTreeDo) FirstOrInit() (*model.TestTree, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestTree), nil
	}
}

func (t testTreeDo) FirstOrCreate() (*model.TestTree, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestTree), nil
	}
}

func (t testTreeDo) FindByPage(offset int, limit int) (result []*model.TestTree, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t testTreeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t testTreeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t testTreeDo) Delete(models ...*model.TestTree) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *testTreeDo) withDO(do gen.Dao) *testTreeDo {
	t.DO = *do.(*gen.DO)
	return t
}
