// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"ovra/app/demo/internal/dal/model"
)

func newTestDemo(db *gorm.DB, opts ...gen.DOOption) testDemo {
	_testDemo := testDemo{}

	_testDemo.testDemoDo.UseDB(db, opts...)
	_testDemo.testDemoDo.UseModel(&model.TestDemo{})

	tableName := _testDemo.testDemoDo.TableName()
	_testDemo.ALL = field.NewAsterisk(tableName)
	_testDemo.ID = field.NewInt64(tableName, "id")
	_testDemo.TenantID = field.NewString(tableName, "tenant_id")
	_testDemo.DeptID = field.NewInt64(tableName, "dept_id")
	_testDemo.UserID = field.NewInt64(tableName, "user_id")
	_testDemo.OrderNum = field.NewInt32(tableName, "order_num")
	_testDemo.TestKey = field.NewString(tableName, "test_key")
	_testDemo.Value = field.NewString(tableName, "value")
	_testDemo.Version = field.NewInt32(tableName, "version")
	_testDemo.CreateDept = field.NewInt64(tableName, "create_dept")
	_testDemo.CreateTime = field.NewTime(tableName, "create_time")
	_testDemo.CreateBy = field.NewInt64(tableName, "create_by")
	_testDemo.UpdateTime = field.NewTime(tableName, "update_time")
	_testDemo.UpdateBy = field.NewInt64(tableName, "update_by")
	_testDemo.DelFlag = field.NewInt32(tableName, "del_flag")

	_testDemo.fillFieldMap()

	return _testDemo
}

// testDemo 测试单表
type testDemo struct {
	testDemoDo testDemoDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	TenantID   field.String // 租户编号
	DeptID     field.Int64  // 部门id
	UserID     field.Int64  // 用户id
	OrderNum   field.Int32  // 排序号
	TestKey    field.String // key键
	Value      field.String // 值
	Version    field.Int32  // 版本
	CreateDept field.Int64  // 创建部门
	CreateTime field.Time   // 创建时间
	CreateBy   field.Int64  // 创建人
	UpdateTime field.Time   // 更新时间
	UpdateBy   field.Int64  // 更新人
	DelFlag    field.Int32  // 删除标志

	fieldMap map[string]field.Expr
}

func (t testDemo) Table(newTableName string) *testDemo {
	t.testDemoDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t testDemo) As(alias string) *testDemo {
	t.testDemoDo.DO = *(t.testDemoDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *testDemo) updateTableName(table string) *testDemo {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TenantID = field.NewString(table, "tenant_id")
	t.DeptID = field.NewInt64(table, "dept_id")
	t.UserID = field.NewInt64(table, "user_id")
	t.OrderNum = field.NewInt32(table, "order_num")
	t.TestKey = field.NewString(table, "test_key")
	t.Value = field.NewString(table, "value")
	t.Version = field.NewInt32(table, "version")
	t.CreateDept = field.NewInt64(table, "create_dept")
	t.CreateTime = field.NewTime(table, "create_time")
	t.CreateBy = field.NewInt64(table, "create_by")
	t.UpdateTime = field.NewTime(table, "update_time")
	t.UpdateBy = field.NewInt64(table, "update_by")
	t.DelFlag = field.NewInt32(table, "del_flag")

	t.fillFieldMap()

	return t
}

func (t *testDemo) WithContext(ctx context.Context) *testDemoDo { return t.testDemoDo.WithContext(ctx) }

func (t testDemo) TableName() string { return t.testDemoDo.TableName() }

func (t testDemo) Alias() string { return t.testDemoDo.Alias() }

func (t testDemo) Columns(cols ...field.Expr) gen.Columns { return t.testDemoDo.Columns(cols...) }

func (t *testDemo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *testDemo) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 14)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tenant_id"] = t.TenantID
	t.fieldMap["dept_id"] = t.DeptID
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["order_num"] = t.OrderNum
	t.fieldMap["test_key"] = t.TestKey
	t.fieldMap["value"] = t.Value
	t.fieldMap["version"] = t.Version
	t.fieldMap["create_dept"] = t.CreateDept
	t.fieldMap["create_time"] = t.CreateTime
	t.fieldMap["create_by"] = t.CreateBy
	t.fieldMap["update_time"] = t.UpdateTime
	t.fieldMap["update_by"] = t.UpdateBy
	t.fieldMap["del_flag"] = t.DelFlag
}

func (t testDemo) clone(db *gorm.DB) testDemo {
	t.testDemoDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t testDemo) replaceDB(db *gorm.DB) testDemo {
	t.testDemoDo.ReplaceDB(db)
	return t
}

type testDemoDo struct{ gen.DO }

func (t testDemoDo) Debug() *testDemoDo {
	return t.withDO(t.DO.Debug())
}

func (t testDemoDo) WithContext(ctx context.Context) *testDemoDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t testDemoDo) ReadDB() *testDemoDo {
	return t.Clauses(dbresolver.Read)
}

func (t testDemoDo) WriteDB() *testDemoDo {
	return t.Clauses(dbresolver.Write)
}

func (t testDemoDo) Session(config *gorm.Session) *testDemoDo {
	return t.withDO(t.DO.Session(config))
}

func (t testDemoDo) Clauses(conds ...clause.Expression) *testDemoDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t testDemoDo) Returning(value interface{}, columns ...string) *testDemoDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t testDemoDo) Not(conds ...gen.Condition) *testDemoDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t testDemoDo) Or(conds ...gen.Condition) *testDemoDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t testDemoDo) Select(conds ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t testDemoDo) Where(conds ...gen.Condition) *testDemoDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t testDemoDo) Order(conds ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t testDemoDo) Distinct(cols ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t testDemoDo) Omit(cols ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t testDemoDo) Join(table schema.Tabler, on ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t testDemoDo) LeftJoin(table schema.Tabler, on ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t testDemoDo) RightJoin(table schema.Tabler, on ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t testDemoDo) Group(cols ...field.Expr) *testDemoDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t testDemoDo) Having(conds ...gen.Condition) *testDemoDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t testDemoDo) Limit(limit int) *testDemoDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t testDemoDo) Offset(offset int) *testDemoDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t testDemoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *testDemoDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t testDemoDo) Unscoped() *testDemoDo {
	return t.withDO(t.DO.Unscoped())
}

func (t testDemoDo) Create(values ...*model.TestDemo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t testDemoDo) CreateInBatches(values []*model.TestDemo, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t testDemoDo) Save(values ...*model.TestDemo) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t testDemoDo) First() (*model.TestDemo, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestDemo), nil
	}
}

func (t testDemoDo) Take() (*model.TestDemo, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestDemo), nil
	}
}

func (t testDemoDo) Last() (*model.TestDemo, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestDemo), nil
	}
}

func (t testDemoDo) Find() ([]*model.TestDemo, error) {
	result, err := t.DO.Find()
	return result.([]*model.TestDemo), err
}

func (t testDemoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TestDemo, err error) {
	buf := make([]*model.TestDemo, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t testDemoDo) FindInBatches(result *[]*model.TestDemo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t testDemoDo) Attrs(attrs ...field.AssignExpr) *testDemoDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t testDemoDo) Assign(attrs ...field.AssignExpr) *testDemoDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t testDemoDo) Joins(fields ...field.RelationField) *testDemoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t testDemoDo) Preload(fields ...field.RelationField) *testDemoDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t testDemoDo) FirstOrInit() (*model.TestDemo, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestDemo), nil
	}
}

func (t testDemoDo) FirstOrCreate() (*model.TestDemo, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TestDemo), nil
	}
}

func (t testDemoDo) FindByPage(offset int, limit int) (result []*model.TestDemo, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t testDemoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t testDemoDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t testDemoDo) Delete(models ...*model.TestDemo) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *testDemoDo) withDO(do gen.Dao) *testDemoDo {
	t.DO = *do.(*gen.DO)
	return t
}
