// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package sysrpc

import (
	"context"

	"ovra/app/system/pb/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClientInfoReq  = system.ClientInfoReq
	ClientInfoResp = system.ClientInfoResp
	EmptyReq       = system.EmptyReq
	EmptyResp      = system.EmptyResp
	LoginInfoReq   = system.LoginInfoReq
	LoginReq       = system.LoginReq
	LoginResp      = system.LoginResp
	OperLogReq     = system.OperLogReq
	TenantInfo     = system.TenantInfo
	TenantListResp = system.TenantListResp
	UserInfoReq    = system.UserInfoReq
	UserInfoResp   = system.UserInfoResp

	SysRpc interface {
		UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
		ClientInfo(ctx context.Context, in *ClientInfoReq, opts ...grpc.CallOption) (*ClientInfoResp, error)
		SysLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		TenantList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*TenantListResp, error)
		LoginInfoSave(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*EmptyResp, error)
		OperLogSave(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultSysRpc struct {
		cli zrpc.Client
	}
)

func NewSysRpc(cli zrpc.Client) SysRpc {
	return &defaultSysRpc{
		cli: cli,
	}
}

func (m *defaultSysRpc) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultSysRpc) ClientInfo(ctx context.Context, in *ClientInfoReq, opts ...grpc.CallOption) (*ClientInfoResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.ClientInfo(ctx, in, opts...)
}

func (m *defaultSysRpc) SysLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.SysLogin(ctx, in, opts...)
}

func (m *defaultSysRpc) TenantList(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*TenantListResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.TenantList(ctx, in, opts...)
}

func (m *defaultSysRpc) LoginInfoSave(ctx context.Context, in *LoginInfoReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.LoginInfoSave(ctx, in, opts...)
}

func (m *defaultSysRpc) OperLogSave(ctx context.Context, in *OperLogReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := system.NewSysRpcClient(m.cli.Conn())
	return client.OperLogSave(ctx, in, opts...)
}
