// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserPost = "sys_user_post"

// SysUserPost 用户与岗位关联表
type SysUserPost struct {
	UserID string `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"` // 用户ID
	PostID string `gorm:"column:post_id;primaryKey;comment:岗位ID" json:"post_id"` // 岗位ID
}

// TableName SysUserPost's table name
func (*SysUserPost) TableName() string {
	return TableNameSysUserPost
}
