// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysPost = "sys_post"

// SysPost 岗位信息表
type SysPost struct {
	PostID       string    `gorm:"column:post_id;primaryKey;comment:岗位ID" json:"post_id"`         // 岗位ID
	TenantID     string    `gorm:"column:tenant_id;default:000000;comment:租户编号" json:"tenant_id"` // 租户编号
	DeptID       string    `gorm:"column:dept_id;not null;comment:部门id" json:"dept_id"`           // 部门id
	PostCode     string    `gorm:"column:post_code;not null;comment:岗位编码" json:"post_code"`       // 岗位编码
	PostCategory string    `gorm:"column:post_category;comment:岗位类别编码" json:"post_category"`      // 岗位类别编码
	PostName     string    `gorm:"column:post_name;not null;comment:岗位名称" json:"post_name"`       // 岗位名称
	PostSort     int32     `gorm:"column:post_sort;not null;comment:显示顺序" json:"post_sort"`       // 显示顺序
	Status       string    `gorm:"column:status;not null;comment:状态（0正常 1停用）" json:"status"`      // 状态（0正常 1停用）
	CreateDept   int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`            // 创建部门
	CreateBy     int64     `gorm:"column:create_by;comment:创建者" json:"create_by"`                 // 创建者
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`            // 创建时间
	UpdateBy     int64     `gorm:"column:update_by;comment:更新者" json:"update_by"`                 // 更新者
	UpdateTime   time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`            // 更新时间
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                        // 备注
}

// TableName SysPost's table name
func (*SysPost) TableName() string {
	return TableNameSysPost
}
