// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOss = "sys_oss"

// SysOss OSS对象存储表
type SysOss struct {
	OssID        string    `gorm:"column:oss_id;primaryKey;comment:对象存储主键" json:"oss_id"`            // 对象存储主键
	TenantID     string    `gorm:"column:tenant_id;default:000000;comment:租户编号" json:"tenant_id"`    // 租户编号
	FileName     string    `gorm:"column:file_name;not null;comment:文件名" json:"file_name"`           // 文件名
	OriginalName string    `gorm:"column:original_name;not null;comment:原名" json:"original_name"`    // 原名
	FileSuffix   string    `gorm:"column:file_suffix;not null;comment:文件后缀名" json:"file_suffix"`     // 文件后缀名
	URL          string    `gorm:"column:url;not null;comment:URL地址" json:"url"`                     // URL地址
	Ext1         string    `gorm:"column:ext1;comment:扩展字段" json:"ext1"`                             // 扩展字段
	CreateDept   int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`               // 创建部门
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`               // 创建时间
	CreateBy     int64     `gorm:"column:create_by;comment:上传人" json:"create_by"`                    // 上传人
	UpdateTime   time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`               // 更新时间
	UpdateBy     int64     `gorm:"column:update_by;comment:更新人" json:"update_by"`                    // 更新人
	Service      string    `gorm:"column:service;not null;default:minio;comment:服务商" json:"service"` // 服务商
}

// TableName SysOss's table name
func (*SysOss) TableName() string {
	return TableNameSysOss
}
