// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOssConfig = "sys_oss_config"

// SysOssConfig 对象存储配置表
type SysOssConfig struct {
	OssConfigID  string    `gorm:"column:oss_config_id;primaryKey;comment:主键" json:"oss_config_id"`                                         // 主键
	TenantID     string    `gorm:"column:tenant_id;default:000000;comment:租户编号" json:"tenant_id"`                                           // 租户编号
	ConfigKey    string    `gorm:"column:config_key;not null;comment:配置key" json:"config_key"`                                              // 配置key
	AccessKey    string    `gorm:"column:access_key;comment:accessKey" json:"access_key"`                                                   // accessKey
	SecretKey    string    `gorm:"column:secret_key;comment:秘钥" json:"secret_key"`                                                          // 秘钥
	BucketName   string    `gorm:"column:bucket_name;comment:桶名称" json:"bucket_name"`                                                       // 桶名称
	Prefix       string    `gorm:"column:prefix;comment:前缀" json:"prefix"`                                                                  // 前缀
	Endpoint     string    `gorm:"column:endpoint;comment:访问站点" json:"endpoint"`                                                            // 访问站点
	Domain       string    `gorm:"column:domain;comment:自定义域名" json:"domain"`                                                               // 自定义域名
	IsHTTPS      string    `gorm:"column:is_https;default:N;comment:是否https（Y=是,N=否）" json:"is_https"`                                      // 是否https（Y=是,N=否）
	Region       string    `gorm:"column:region;comment:域" json:"region"`                                                                   // 域
	AccessPolicy string    `gorm:"column:access_policy;not null;default:1;comment:桶权限类型(0=private 1=public 2=custom)" json:"access_policy"` // 桶权限类型(0=private 1=public 2=custom)
	Status       string    `gorm:"column:status;default:1;comment:是否默认（0=是,1=否）" json:"status"`                                             // 是否默认（0=是,1=否）
	Ext1         string    `gorm:"column:ext1;comment:扩展字段" json:"ext1"`                                                                    // 扩展字段
	CreateDept   int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`                                                      // 创建部门
	CreateBy     int64     `gorm:"column:create_by;comment:创建者" json:"create_by"`                                                           // 创建者
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                                                      // 创建时间
	UpdateBy     int64     `gorm:"column:update_by;comment:更新者" json:"update_by"`                                                           // 更新者
	UpdateTime   time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                                                      // 更新时间
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                                                                  // 备注
}

// TableName SysOssConfig's table name
func (*SysOssConfig) TableName() string {
	return TableNameSysOssConfig
}
