// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package server

import (
	"context"

	"ovra/app/system/internal/logic/sysrpc"
	"ovra/app/system/internal/svc"
	"ovra/app/system/pb/system"
)

type SysRpcServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSysRpcServer
}

func NewSysRpcServer(svcCtx *svc.ServiceContext) *SysRpcServer {
	return &SysRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *SysRpcServer) UserInfo(ctx context.Context, in *system.UserInfoReq) (*system.UserInfoResp, error) {
	l := sysrpclogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}

func (s *SysRpcServer) ClientInfo(ctx context.Context, in *system.ClientInfoReq) (*system.ClientInfoResp, error) {
	l := sysrpclogic.NewClientInfoLogic(ctx, s.svcCtx)
	return l.ClientInfo(in)
}

func (s *SysRpcServer) SysLogin(ctx context.Context, in *system.LoginReq) (*system.LoginResp, error) {
	l := sysrpclogic.NewSysLoginLogic(ctx, s.svcCtx)
	return l.SysLogin(in)
}

func (s *SysRpcServer) TenantList(ctx context.Context, in *system.EmptyReq) (*system.TenantListResp, error) {
	l := sysrpclogic.NewTenantListLogic(ctx, s.svcCtx)
	return l.TenantList(in)
}

func (s *SysRpcServer) LoginInfoSave(ctx context.Context, in *system.LoginInfoReq) (*system.EmptyResp, error) {
	l := sysrpclogic.NewLoginInfoSaveLogic(ctx, s.svcCtx)
	return l.LoginInfoSave(in)
}

func (s *SysRpcServer) OperLogSave(ctx context.Context, in *system.OperLogReq) (*system.EmptyResp, error) {
	l := sysrpclogic.NewOperLogSaveLogic(ctx, s.svcCtx)
	return l.OperLogSave(in)
}
